### ISSUE TITLE
Implement Aggregation

### ISSUE THREAD

**Issue by heynemann** [heynemann/motorengine#46]
Allow users to aggregate data using the new Aggregation Pipeline(http://docs.mongodb.org/manual/core/aggregation-pipeline/):

```
class Product(Document):
    type = StringField()
    location = StringField()
    price = FloatField()
    stocked = IntField()
    is_active = BooleanField()

Document.objects.filter(is_active=True).order_by("type").aggregate(
    group_by=[Document.type, Document.location],
    price=Aggregation.add_to_set(Document.price),
    stocked=Aggregation.add_to_set(Document.stocked)
)
```

The types of aggregation are in the following tickets:
- [ ] Implement add_to_set aggregation - #47
- [ ] Implement first aggregation - #48
- [ ] Implement last aggregation - #49
- [ ] Implement max aggregation - #50
- [ ] Implement min aggregation - #51
- [x] Implement avg aggregation - #52
- [ ] Implement push aggregation - #53
- [ ] Implement sum aggregation - #54
- [ ] Implement count aggregation - #55
